# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: honcho-secret
stringData:
    HONCHO_DBNAME: ENC[AES256_GCM,data:zOc8AZ/x,iv:ZvpgOFkNeU6hQsSUcxzii9xU7pcQpRefWqX1WFV/uu8=,tag:LrJUCAI5raY29NHFHsEYWg==,type:str]
    HONCHO_DB_USER: ENC[AES256_GCM,data:fj9AVz53,iv:m/7uYMtx+QAsC+ChLaJhEyGad8jNQkegSeuNs1MWVe0=,tag:z8VTFZj/urpCxhAoq6Z06g==,type:str]
    HONCHO_DB_PASS: ENC[AES256_GCM,data:U7dHFUlXdByJmxY0OKvnsf0=,iv:orIhZ7qA+FpIBlsnsYHgD4FW/X0ZbCfWGX9xixrTtJk=,tag:TLRN1Joa0ZAqXE0Fryg0Tg==,type:str]
    LLM_OPENAI_API_KEY: ENC[AES256_GCM,data:TczgQaONNAoaAIwnyHFRFmNVlrb0xDy5br1aGEk7Rt4h4AlI2VP3Hx1v3wTSSHQNC5eijPFDceA/4apJUd7Lq/5BvCIKa3wGlW4VaLnHbTeAi0id0IIn3+7aMDnAz1kg/sO2BEB5RcJw8UwgIbLj14u7+H+rj5a4TdqMid8RpkZZXZk+Ep9GXD7UuwbkCRGuIMiET+fJqwACj408HGdZNQKs+lg=,iv:jPRNF7uEHHmFkBTW/CYegrx8N7mlXmHJEEsooiLz6Eg=,tag:1JKZwUfPUCl2kjpWqNmcww==,type:str]
    LLM_ANTHROPIC_API_KEY: ENC[AES256_GCM,data:EN5ctaqkPvv3CM7EkS7yIHKtioGzIvEZYIzXXViBNLXRCMgXzQ4uKOZ6ykJ7uZx7hJRm/Lp0WGhwQvTWBGAf2wyh8a9NWuU6BZUwfX9AmvamMEVMc5Q12FgV77Zb9F+G7sm34pAsSNB4llZ1,iv:jcQLBC/jPX13Zd3+5Uje26UNcJTvkRrmExhibdew2Kc=,tag:mkEtG1FN2F8nrpLYGZYAqw==,type:str]
    LLM_GEMINI_API_KEY: ENC[AES256_GCM,data:FqXAPl3ldndmDVHf/uuaJqdTcJi7bkdScKDaJFTnKi9pJQM2okLp,iv:CpKhq/sozRr+qqDfzsA9MiomtEAjKsZKDmB12okMrXo=,tag:w1/s7ev6t3HI86LkFrsF4w==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSXljZmJ5d2ZmTFBDWWx0
            NjJSaGp2bWkwdmswNG1XTStMZjJlWm9qRXhRCmp4dFhwQjVEWEk0anRGTldwM3pE
            aS94aUdZZXdvQytMMnVUWFVsMzdKRjgKLS0tIEhyeXNtTHVrcWo4M1FZVXBOSTJu
            VzJMZlhEcmpDTFRyUksvWVozR0dVN0kKfF5mKim1a+LiXC55H1OF1bBRL//Pt9Az
            An7WLGg7/pIXmZx/s1PEhk4GjoS7/faUzbEzds46bgYCCA3PgkZ2LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T17:57:02Z"
    mac: ENC[AES256_GCM,data:QJ1+kjTxu44Cog5jeAIYXXbBJ3iygf3pvt9O6/7zX5wFzIAHksUZUHNdneKoimdlEmnUXZ/3vgWGCjD/RtnbISrz2jOii/lFUpLxQf+cVudPAJTistaeCQxrRK/vz37W0PXpWb0/FA1dLP/M1R6Zl+Bn+plVfPNhQYzmLBIPfik=,iv:TfL47sbH7af25NOe5SewFi6uJBzB8Mq43pv2E/RqDEU=,tag:e0eZ8PdmHve8gCSEJNdtJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
