---
ansible_user: root

# Armbian overlays for Rock Pi 4B
# See: https://popov.wtf/advanced-armbian-setup-for-rock-pi-4b
armbian_overlays_prefix: rockchip
armbian_overlays_std_list:
  - rk3399-pcie-gen2
armbian_overlays_user_list:
  - name: rockpi-poe
    url: https://github.com/radxa/23w-poe/raw/refs/heads/master/dist/dtb/rockpi-poe.dtbo

# Force filesystem checks on every boot and allow systemd-fsck/initramfs to
# repair errors automatically before mounting the root filesystem.
armbian_overlays_extraargs:
  - fsck.mode=force
  - fsck.repair=yes
