# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics
stringData:
    PUSHOVER_ALERTMANAGER_TOKEN: ENC[AES256_GCM,data:O6f0GWQyajZCd3S8c0Nm8sglINaaIlU+P4oLDRwR,iv:8cOLF6vfI8WlBNiA62PctxI/SSgyq5Gd25qKAQHCZHU=,tag:ZlIZEQmCyEfnK53Sm7nEQg==,type:str]
    ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:3P1jjTzJkLA5HZIDbRM5FbJdW3/wnK1nyhY+UbKMLuo1sSamuMFLC2Us/4w0xOZL11BW2CkQ4t9Vxjiyzdx3szWIhK8ZS5FhyCZr74QtmUUXzL4D0Q==,iv:oMST5pBjTLZH78MOHGGIJfPJgagn9BBJozz59UVrl8k=,tag:qjM7l+OZ9Do27iQTyJB6eQ==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T18:34:56Z"
    mac: ENC[AES256_GCM,data:Uh0y+hnhruNq9E/j854biXwjPup0xB9EYFi2BAPuJL+HUJ1aEUPyRajpzySSdjItdHpwckzbpgBs/WrTgTfCT40AJI6RWD78Cfq14F74ISQsQ99Uu6Kkl0bVi5ggVfSaN2AT4kFwGFuqyhc0n3oGFa/mBeHLwd/GBIJ/Hkup+3M=,iv:Z7fW5PZXzjLX4vVc9lU/mGwqDvigxrcLOFoodgTkl/0=,tag:qCPOpqv5bEAQrqZdSxv2lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
