---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  interval: 1h
  values:
    fullnameOverride: k8s-gateway
    domain: "popov.wtf"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: "10.101.0.200"
      externalTrafficPolicy: Cluster
    watchedResources: ["HTTPRoute", "Service"]
    fallthrough:
      enabled: true
    forward:
      enabled: true
      servers:
        - "10.43.0.10"
    options:
      timeout: 5s
      edns0: true
