---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kured
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.12.1
    digest: sha256:bd7cf702ddee292cc8aa2618e34c500fd2e02df5e19d1907111a9a15a5bfa8b4
  url: oci://ghcr.io/kubereboot/charts/kured
