---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kured
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.11.0
    digest: sha256:f96eb9aad39bfc1c3f36b8546e00c4cb64bff305d17b30bd71ed3b62802e0f27
  url: oci://ghcr.io/kubereboot/charts/kured
