# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: kured-secret
stringData:
    KURED_NOTIFY_URL: ENC[AES256_GCM,data:LkcNTkCMhBuN9d5xW2T8KwExkWcgDVsz/5WqPc3xajxDTVOsEbf+kvvrkVEMQdEVBcVX+dhlr8F5W5aKGMNgexE6J8z7xpoA6TT9jiOX1ZUm,iv:G5YXShNBHRukxg86xab7kKHtNhA9wZ1YhhYQOx9K/N0=,tag:bOBJBGseahl8kbAJ4MrJhQ==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T18:32:45Z"
    mac: ENC[AES256_GCM,data:zYCvXq6Qlb0gtqxWZiUT1ox32NSgW/3cTtAo2XuI8GVUaIpKnmlYg6shBXIwgrxlSgVrp1MfFn0lFzC9fQGdoNvtj4JlUFAW0sqKoOUKNgBX+hxcU0Ijj/TSJRR3GObKhSrsUv/RGbNKZs46W0DnmJeHADSnYO6Jz7KqRzOcMaQ=,iv:3IAPgpMKVkgSl3zM5wNMwQkcfyOskzHTOFv+8Wh/W98=,tag:3q5CoWu2e7MYKV3zT5HPlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
