---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubernetes-mcp-server
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.0@sha256:d195024c399e26a5f08214d2e5967868c67d3f577cc6694b0e8d6a2226638059
  url: oci://ghcr.io/containers/charts/kubernetes-mcp-server
