---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubernetes-mcp-server
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.0
    digest: sha256:0d69a8035c4b5f94029ff7bc7473796065b621f8b88cc17efb40d78d9ee5bb5d
  url: oci://ghcr.io/containers/charts/kubernetes-mcp-server
