---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rockpi-poe-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      rockpi-poe-controller:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/tolkonepiu/rockpi-poe-controller
              tag: v0.3.12
            ports:
              - name: http
                containerPort: &port 8000
                protocol: TCP
            env:
              POE_LV0: 40
              POE_LV1: 45
              POE_LV2: 50
              POE_LV3: 55
              POE_METRICS_PORT: *port
              POE_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              POE_NODE_IP:
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
              privileged: true
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
    defaultPodOptions:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm64
    service:
      app:
        ports:
          metrics:
            port: *port
            targetPort: http
    serviceMonitor:
      app:
        endpoints:
          - port: metrics
    persistence:
      proc-cpu-info:
        type: hostPath
        hostPath: /proc/cpuinfo
        hostPathType: File
        globalMounts:
          - path: /proc/cpuinfo
            readOnly: true
      proc-device-tree:
        type: hostPath
        hostPath: /proc/device-tree
        hostPathType: Directory
        globalMounts:
          - path: /proc/device-tree
            readOnly: true
      thermal:
        type: hostPath
        hostPath: /sys/class/thermal
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/thermal
            readOnly: true
      pwm:
        type: hostPath
        hostPath: /sys/class/pwm
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/pwm
            readOnly: false
      gpiochip0:
        type: hostPath
        hostPath: /dev/gpiochip0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip0
            readOnly: false
      gpiochip1:
        type: hostPath
        hostPath: /dev/gpiochip1
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip1
            readOnly: false
      gpiochip2:
        type: hostPath
        hostPath: /dev/gpiochip2
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip2
            readOnly: false
      gpiochip3:
        type: hostPath
        hostPath: /dev/gpiochip3
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip3
            readOnly: false
      gpiochip4:
        type: hostPath
        hostPath: /dev/gpiochip4
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/gpiochip4
            readOnly: false
      gpio-sysfs:
        type: hostPath
        hostPath: /sys/class/gpio
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/gpio
            readOnly: false
