---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: torrserver
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      torrserver:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/yourok/torrserver
              tag: MatriX.143@sha256:9a6b95f5744af2fcff55c505891c737f22dd6e1d3d53269fc2268ef3382507d9
            env:
              HTTP_PORT: &port 8090
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.101.0.211"
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.popov.wtf"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /opt/ts
