---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - ./instance.yaml
  - ./httproute.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: openclaw-context-config
    files:
      - AGENTS.md=./resources/context/AGENTS.md
      - BOOTSTRAP.md=./resources/context/BOOTSTRAP.md
      - HEARTBEAT.md=./resources/context/HEARTBEAT.md
      - IDENTITY.md=./resources/context/IDENTITY.md
      - MEMORY.md=./resources/context/MEMORY.md
      - SOUL.md=./resources/context/SOUL.md
      - TOOLS.md=./resources/context/TOOLS.md
      - USER.md=./resources/context/USER.md
  - name: openclaw-transforms-config
    files:
      - alertmanager.js=./resources/transforms/alertmanager.js
generatorOptions:
  disableNameSuffixHash: true
