# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:lWVA9YXs3hTeB8CQfMrxt/w8FqyOtBTDFAdZItygCXIMsxbtxI7WkbYrrVnrgyPZNEudNtzPLdB5u1/iS95Ifg==,iv:ZVe6B6hXaVbbBEM3yaphIdit+03xVe7PgmoOmsIor+E=,tag:28BcgSOn/tRSoPWyiszucg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:fkC789o=,iv:CKK9lkIvt21IYVjfGIma1K6uJ/1l2bgFeNaKlHXVYrE=,tag:ls1s5qgVKcODap2Ic/Sx/w==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:8wQXsnpl+j5psQ==,iv:8jMmpqx6uhJSczVGDzNZ7kOX3oWOk/Vfh+/wVdNyau4=,tag:vbGINdCaK0NeU3H2mH8sgA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:y5JfoCQOQC5/7uj3oETatj1l+eISSAq6yaV+4sJw67JrGJKw08Fi8NKhzf8=,iv:GlX5dZHB0gRmxy/YYVefr9kb4IvcOVVCH1RECFfKu74=,tag:UVAVhtAK7HpGd7hKbZerkw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:wlupktD5zKq/GFQx4XCgVkPLWi+iHbXuIUDfMwjxQl44y5d5oqbI1Orh7av6Ng==,iv:mHsb9VRQS2jaCc8atXnGxNI23rtyYT00xQqyjmak3bw=,tag:3RZ5h9vx6yNSEXoLG5kSjw==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:lXuIU9arQGrKDjo0LP+ivwUm1Lp7OHdH0DIu,iv:IeN6XsncUCsxSaP+aodKxVRTENedPNXs3eTE1PbxdMs=,tag:OXSFTSsgZU3SKZivjhIUug==,type:str]
    TELEGRAM_GROUP_ALLOWED_CHATS: ENC[AES256_GCM,data:UbT8NjfTYyr4lE2Q9d0=,iv:IvHN9qA5n1+3fGdBtsxNoFQS9BQ48IPS+4BN9pdc0h8=,tag:UpCPQLocP4ynVWzmn/xl/w==,type:str]
    TELEGRAM_HOME_CHANNEL: ENC[AES256_GCM,data:UV/Dp+1Ja9sZQQjRV6Q=,iv:D7NFRu+j3eNfuHl3SV/9gMxWkRcVPFEgQMiwLhaYHs0=,tag:9itJKsTQQc3hq0HE8tVdsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T08:46:51Z"
    mac: ENC[AES256_GCM,data:TlEO0GmKe4vySw8e3GXgI2KOlx7ykUSorw5tgur6ch7OpQIuu6h3AWjuJIBURU0clVgxQRpKizw+wtPd8ubb4hjD+fQD6ydgL/4ZJOP+dQHK4BPDEX+WM72z2Hp7mpr2kFAua+1qw0CLpeMslNqXHKcRjDXqJf47JTbU9TxtRs8=,iv:lNoD3ace0+pwbpwDTrmznSu1JPG9C813A1VDp6VXr/k=,tag:K503FpNDSaUEVdCvdslNyg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
