# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:lWVA9YXs3hTeB8CQfMrxt/w8FqyOtBTDFAdZItygCXIMsxbtxI7WkbYrrVnrgyPZNEudNtzPLdB5u1/iS95Ifg==,iv:ZVe6B6hXaVbbBEM3yaphIdit+03xVe7PgmoOmsIor+E=,tag:28BcgSOn/tRSoPWyiszucg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T16:14:28Z"
    mac: ENC[AES256_GCM,data:LIkv5H0oZmqZbcJ7C5VXvZTyXLKpHMkrq0qV8CWx1ryizkx5HSINjP6gIl3bRHrPa8foPXTEfvjfvGdcv2yLcodTjuZ55IiElXk4DwI6HYH6bqtnDgOuYwIk+iO4YaxynRLc+XQJv1VIr5RPMW3Xbmtic5XdFJBAmSntCjB+le8=,iv:l4azSZ8OdEMGmJ8VIHwj2vJTB/PhIiqnt1B/3g/x2RA=,tag:u9gGS2T8MtTKGubf+iXXRg==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
