# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:lWVA9YXs3hTeB8CQfMrxt/w8FqyOtBTDFAdZItygCXIMsxbtxI7WkbYrrVnrgyPZNEudNtzPLdB5u1/iS95Ifg==,iv:ZVe6B6hXaVbbBEM3yaphIdit+03xVe7PgmoOmsIor+E=,tag:28BcgSOn/tRSoPWyiszucg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:hSufnbBm3CSQJbYAmxEdVPpbL3gOFA0Mk/ppkGuF+PaVBc/5emJExkOD7by+kA==,iv:NdbnmM2J2nf7BFkEppuochxmFtJkwBxrT6IuXapXmi4=,tag:II085JlFT3chsnBvHVeVoA==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:XE0Pe/Df2jF/C1BhtG7GNfQIyb/SdyV4qc0f,iv:TxlUJ69t1j34HnjJ5RZDa7eoK+lRx1kw12NNM/pSLm8=,tag:egq45ux4krkoEofLvaz2QQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUFhnVVJleHFqS3NlcXRC
            VHluMDdpMlhhYjlnUGVJWC9xQWlrSVRVRjJjCnpIdXBuZWJVTUdCUmxiZ1N6QktO
            OUNqdXNVenYzNUtGMGRUUHRsa0RVa1UKLS0tIDJjZU4xSEJYWUQvcFdySlhaY0VR
            dE5pOU84eFJ6WnFFa0gxaGc2TFFjNVUKK+/d3LL1Bf+A2WRtmyGR9Dnq3qNH+20J
            p3sauiuH5dWx/twrS+k8QfJZyOkt5D4zqpmWthV21fSdYOUiciJhXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T17:36:09Z"
    mac: ENC[AES256_GCM,data:4cVIEEis/X0PSpl7EDlaYwX60v6fDqhINoaun+IJPsmamDvfrkNG6210nshMS2cP0rA2KlHfs4o3rylVUrUqV8aPxblZxJiOuU1toqSpFo8mzSJ/dir28e0I54KwwA2fY9GmR7XBPSyY20DqPRdrp4MLS6VGjr2vqMIZnn6AU9g=,iv:a7+qDsWgspfrqhKbCWhAJwHMdjq0xWLfz3gPBAVAqw4=,tag:330PwrAY9Idui7Rj7UR6Aw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
