---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  chartRef:
    kind: OCIRepository
    name: grafana
  interval: 1h
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    deploymentStrategy:
      type: Recreate
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 384Mi
        cpu: 500m
    env:
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_EXPLORE_ENABLED: true
    grafana.ini:
      news:
        news_feed_enabled: false
      server:
        root_url: https://grafana.popov.wtf
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      auth.anonymous:
        enabled: true
        org_id: 1
        org_name: Main Org.
        org_role: Viewer
      log:
        mode: console
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - { name: Prometheus, orgId: 1 }
          - { name: Alertmanager, orgId: 1 }
        datasources:
          - name: Prometheus
            type: prometheus
            uid: prometheus
            access: proxy
            url: http://vmsingle-stack.observability.svc.cluster.local:8428
          - name: Alertmanager
            type: alertmanager
            uid: alertmanager
            access: proxy
            url: http://vmalertmanager-stack.observability.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: kubernetes
            orgId: 1
            folder: Kubernetes
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/kubernetes
          - name: victoria-metrics
            orgId: 1
            folder: VictoriaMetrics
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/victoria-metrics
    dashboards:
      default:
        cloudflared:
          # renovate: depName="Cloudflare Tunnels (cloudflared)"
          gnetId: 17457
          revision: 6
          datasource:
            - name: DS_PROMETHEUS
              value: Prometheus
        node-exporter-full:
          # renovate: depName="Node Exporter Full"
          gnetId: 1860
          revision: 45
          datasource: Prometheus
        cert-manager:
          # renovate: depName="Cert-manager-Kubernetes"
          gnetId: 20842
          revision: 3
          datasource: Prometheus
      kubernetes:
        kubernetes-api-server:
          # renovate: depName="Kubernetes / System / API Server"
          gnetId: 15761
          revision: 21
          datasource: Prometheus
        kubernetes-coredns:
          # renovate: depName="Kubernetes / System / CoreDNS"
          gnetId: 15762
          revision: 22
          datasource: Prometheus
        kubernetes-global:
          # renovate: depName="Kubernetes / Views / Global"
          gnetId: 15757
          revision: 43
          datasource: Prometheus
        kubernetes-namespaces:
          # renovate: depName="Kubernetes / Views / Namespaces"
          gnetId: 15758
          revision: 46
          datasource: Prometheus
        kubernetes-nodes:
          # renovate: depName="Kubernetes / Views / Nodes"
          gnetId: 15759
          revision: 40
          datasource: Prometheus
        kubernetes-pods:
          # renovate: depName="Kubernetes / Views / Pods"
          gnetId: 15760
          revision: 39
          datasource: Prometheus
        etcd:
          # renovate: depName="Etcd Cluster Overview"
          gnetId: 21473
          revision: 3
          datasource: Prometheus
      victoria-metrics:
        operator:
          url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/refs/heads/master/dashboards/operator.json
          datasource: Prometheus
        victoriametrics:
          url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/refs/heads/master/dashboards/victoriametrics.json
          datasource: Prometheus
        vmagent:
          url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/refs/heads/master/dashboards/vmagent.json
          datasource: Prometheus
        vmalert:
          url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/refs/heads/master/dashboards/vmalert.json
          datasource: Prometheus
        alert-statistics:
          url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/refs/heads/master/dashboards/alert-statistics.json
          datasource: Prometheus
        mcp-victoriametrics:
          url: https://raw.githubusercontent.com/VictoriaMetrics/mcp-victoriametrics/refs/heads/main/dashboard/mcp-victoriametrics-grafana.json
          datasource: Prometheus
    sidecar:
      image:
        registry: ghcr.io
        repository: home-operations/k8s-sidecar
        tag: 2.11.1@sha256:2dce54e06b1a79d1abed2089933551dd2c02a6e3d45fb5ab1ee1bc6bb6cc5834
      dashboards:
        enabled: true
        searchNamespace: ALL
        resource: configmap
        labelValue: ""
        label: grafana_dashboard
        folderAnnotation: grafana_folder
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
      datasources:
        enabled: false
        searchNamespace: ALL
        labelValue: ""
        label: grafana_datasource
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          memory: 256Mi
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: true
    route:
      main:
        enabled: true
        hostnames: ["{{ .Release.Name }}.popov.wtf"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      enabled: false
