---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openclaw-operator
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: openclaw-operator
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cluster-secrets
                      key: GITHUB_TOKEN
  values:
    metrics:
      secure: false
      serviceMonitor:
        enabled: true
