# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:N1eU1UVGOPXccDJHHxxuBPY=,iv:DUQx5BNZlIjy/ec4dqJsLaThyYIB5MEB2aI8gDu6yjs=,tag:fJk6dLAOdt3oReafthk/Mg==,type:str]
    client_secret: ENC[AES256_GCM,data:1mZv2tixyuHZ0IxbupHGGSSJz3j1rWknHw38rwzwBSDaIp/GZ/oyRmQv2OlsNjDq0Na01WTMbjWTh+CTfZHr,iv:cDMH6tU9o4pMpM5Bu39Bz2QGAcYHPCS0xuGe2oXFbwE=,tag:/yL9hAlgWMKkTQjOlQAA4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ckVQSGRDc3pvdHg3UHVu
            dC8vc0dtV0hKU29jTnJUYUhDMndSRWNSb0J3ClpST0VZQkVDNDJGa3RxT2R3Ynlo
            cjF0ZytMV1dQNWc1Zm13VzY4RjlZMGcKLS0tIFM1Zk5UOFJWOXJZY0ZIZGRMRlVT
            eVQzalBrU255RzdERGFkdXZJU0JnYjgKgS04M/hCQWzc7UBNC61XJeGMsX401s7J
            V+x0KkpNDc/70lRn+HFK2wpfcwXKs23qARecI7yZKuDajMwiWTM43Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T05:02:16Z"
    mac: ENC[AES256_GCM,data:54gqJD5jE1lMZIOLKiu3KueZ9oSdi29gxIr4ZXclyeGoaWsrsQVCWxIsSv6N8rKpIKsPexAwFj6bc6ZOpgrg7swB72G90DMlE6WkqqRyh5efTNPcrhIQ9dBWkZn54mzGf08nw369iIVBXE/hClafCCHyfuAeprhUKrd6mEnTHZs=,iv:1sJTKSYqZ7xjq87/D+mY0cP7NH45It24NdM3tyS6YRA=,tag:Aj3/9hRdDx7X/r6C8wIe6g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
