# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:C4S7Hq+iggy3dJd6ncKiSlQvnW52l9ZhWqTsG6ZFEOa7vTLP4dHrdBDwHaSIb2FLVBjHHYX6fOlBMgxW6sewmjcc1LyngeT9VCaj9dYuqSVt7mD3/lC1fHOZKws0Hz/cWqICmyENijl8lVBR59BLBwBazjEAPrDODJJE2OeGj5HUghx4VbmRqyqU78hsfyqc2AYMqNZH3abbFzK6CNtqO0HsW6S4hFh/NtY4CQBqhYt2hJfZ,iv:Ob433uwgLIKTeWOo7i4KgKS3Lfkybw1gQgreTp6iDEE=,tag:fbQXvMk7JY0DHq4QNx83zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMlN6d0F1bnNzWXNIdElY
            b0VLL0JaTXd3a2l0QS9ZZFBIU3c1azYza2xnCjhzUUxWR05sWXordGdQejF1aEVv
            N0lkYTJPN2pYS1dWMUdTUHNrdW03R3cKLS0tIDZibWRkWjBxdkRRZFd4TlJoTlRl
            OE5SbSs1eEdoZHlmNXRIdnIrb2hTSjAK2j4H02gPwwUKHLNZEs+7k3sLiCGGDR1C
            XopdbajCLEXT24Ka7guO92tgSEnMeckbA0bwFIy02IDvonRLPRysUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T05:01:45Z"
    mac: ENC[AES256_GCM,data:5F526GAJlZWjZLjJQhrukHTucRl/NNBi9kV9Nrl+4vOY4fWv4zeIKG2VbiaEI5fxOOJ08oyMTXLV6LtF+1/SU1GDHk3gW7sOtfyxMRhGPFCVV1ejN9GWIlpyJ5baTQlHfESgpjfVjAYl7e9Nn59nVxFz84SXvPyK8Ys0QU36xFw=,iv:91XrUyeMyTxZARMBQ7k90KwfCaxePCM5TsOGF5XeUk8=,tag:l/Gb8cFavCq4boEGDWKqZQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
