---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: isponsorblocktv-scripts
    files:
      - youtube-healthcheck.py=./resources/youtube-healthcheck.py
generatorOptions:
  disableNameSuffixHash: true
