apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-config
    namespace: default
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:1kChNg+PUranTMR1coPJHQSYz6OgiBIT2zv/MZR/GTuUxhmCz+2zp+xM2oLT1hdj0pRyzIFxf5sEoklMoaG0idhS8Nkqy3idJOpK+lVwMSN3WmBM9n2ZhGARoDTMKlB6g2TIaXeZm+4Nbe+wf3ru9pBy+fv0lgfJ0jE32aD4pYljFTrq9PR67Afs0TfsgN5ouELwrrdnvreUT26p5NYPJ1s/D38f1qroIYovh90NB97xbvOoptV6uRo+AydxT9l481nNrbTmgyxdrqG+UTRLIJZHF5WQujiPg5hiDFsyRmOQ/5MJQhcs3wa4mflPDE6byA91vaSKLxfNRp9SDEqXQlbRBMgegCYrQyqSKYjfnWyWOVjNIfuwDgBqTg81dRfwkcVqCe/6Lagoz+rMyyaCKC6n3MFWTHTyuJnpHpBgLoIVcsa9q+QCKiMPc+LUjyxArJfCr7Sqonev9htWbOa4OV1TiYeoRZnxYf+HHHgkt8Ac/BpmGgwzUpOjrMR9bTqva4RW6h5Ccyu0SibvN0dHlZLZdbfofMKouHPYPgm5E/oJNi40Fs/APpXM2DX2wz2ijApdYauITn/TE4MaYjqGXgd3GGZiilq34UCZmg2b1Ch/jDKZIXD9YiBcO7nQRH5So2Or0+pJdR9ITxVt7zd6DQXgveP055AILKXuOHHcapDu2eqko+AmQT/C+cZS6ohFSZVF6UQiH81DYR3RK4++AOJHRPeJeFs5cYbZjFd8qyzQr0X7RyBc5/4395MptdrvQrUudeBQxR7fqnBYWKpRIw8hhZTVz1xxkD7/,iv:PZXBH8+7rFaUW4w54jR02hjXvG+87XjV6UHcRrboWtQ=,tag:MslL/GS1kEPGprD1p4kuzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T14:45:00Z"
    mac: ENC[AES256_GCM,data:V0OkdrKT6vgEjCqIgaXgbbj2xN1NKgkj9TZJuq4hJxZwZoAWXDfhAMEK8MKa7lt6eCKeYQknAf51h9zWTXB+e5x9/SmXwm9mIeptvSYEZ39GimV9LWGVRfDpdHgLx9zqXEqiha/uCiVX6HlcWX87meCHGshVjdZ+MmNYhImBSOA=,iv:iz4N0NKaLcbAhOo1nYsXKtY/uQ35BLMemhbcxJGLK/I=,tag:YLT/HgK7u+PszBtHqtiHhQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
