apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-config
    namespace: default
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:DYal+PSfnaXYWyGNeplAoduDH6hz3NFwUNcBI0T0D7GbXuM6qQrbnNM3orI6JwKKi6Yey8IYtCRdxq0xcGWYideqx07W9xOH9AXek/KFzOM2LoVU77QKpV2AULTubSlSxH1coMlkPYTuWJn44B4bYK/mMk6JjwRIrvLo/Y+9Vl9S9kpRCH3fNUS/aK7JM2EOgwlhRKVLF0jQQaxSrp5iGMjHrebgmVS+icpk/8LwlOCCzNJ4k7ql0EPQwj99BUJjJH/dykLeOVBrpmk+eiU2O1dJheSQ8DGkNvCjYRlFFscEDXwoEi16jwijmjvuKN9aAehFNtI64iJRhgRo8/OMz4GOp3legcVSGubQa/S26rsNpiwLClBFyQZEHTNrlhiv5pnQheF4LfT/rqD2xa8vWZa93WdNwPPkbVwtmexLatA9lKEyDUjJaWtheaW0Yy7G/TxrM+gyI8QGHKr5GfIhIS1GHZEhFZaks/rahdN9K9RDc7iOs1BeRF/o+icNwErqPDhKPvh6nupXWIRH6Beli/5QWoD0gkhhyZTtCGZyMDuQenAbOYrmv2nhPyX2aXWbHVPEk2BsMIznh1PxReabfh6nC780,iv:YTMFQVYl6DsADrUPC/mBDdxqWpD3ITPjZrmv0DD0GXE=,tag:Dd1tk2bzr5lVdtjHH2jmIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVdkNW5rNVVWNVJyWjVv
            cDlUUk1scHBNdWVUUk9PZCtXUUpNczhmbGlnCmVoNFA3SzgzL1ozZDhCc0x2ajNV
            NnljM282TVZhSE1kNFQ0M0VudHdjcVEKLS0tIHUvZE91YnRaMXpHcVFTbklGNEpy
            c1ZoaDhyOWZUZjg1SGc4VnlsdnJuRUUKKhwujAmAg5Y5itKIV33wMogGdw6crs2H
            xzZ3eYM0T/JcnR6N2kEUf6U3IEX3gCUKHOyysBgYn1crZWQLHIr6pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T04:38:34Z"
    mac: ENC[AES256_GCM,data:BQ58xjVVudYrAyN9M1yt68B5KqV1IGUBb3LGSe/SUgwojyU1FDYagdpd00w4tSj1k870naxU361rv+tn7TKfySYFCcsPX2gP5LsBSH74GJXfAY2ntsG2XKH5F5rx8em5MyLqVIuGn81ypOOvmg/FrYgfReJBSyeLVLDh+Lg62KY=,iv:PmVlRscNZ166Jboh5beqSR81+kRI7TXdVP0ryeDwzAo=,tag:fN+uY63xJl/KouKsn3r9nw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
