---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator-mcp
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator-mcp
  interval: 1h
  values:
    transport: http
    readonly: true
    rbac:
      create: true
    networkPolicy:
      create: false
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      hostnames:
        - flux-operator-mcp.popov.wtf
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
