---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.56.0
    digest: sha256:37e9f9943f1e332431c302c2e8148c430ae91cd5bf89af64c90ff5e3b1b2f68b
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
