---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.55.0
    digest: sha256:7c19ccae51000461b14ffeb449d1f486a3e7d884790e7e5f24786e18b2214cf3
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
