---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.60.0
    digest: sha256:2511dc0c3ef25d52d57ebbb001b3d9f667a5ea52d36a0684d04e1fbf09d065bc
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
