---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
components:
  - ../../components/common
resources:
  - ./flux-operator-mcp/ks.yaml
  - ./honcho/ks.yaml
  - ./kubernetes-mcp-server/ks.yaml
  - ./mcp-victoriametrics/ks.yaml
  - ./openclaw-operator/ks.yaml
  - ./openclaw/ks.yaml
