---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rockpi-poe-controller
  namespace: &namespace hardware
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/component: poe-controller
      app.kubernetes.io/part-of: hardware-management
      topology.kubernetes.io/zone: cluster
      node-type: rockpi
  interval: 1h
  path: ./kubernetes/apps/hardware/rockpi-poe-controller/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
