---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app umami
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      umami:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom:
              - secretRef:
                  name: umami-secret
            env:
              - name: INIT_POSTGRES_HOST
                value: tolstoy-rw.database.svc.cluster.local
              - name: INIT_POSTGRES_PORT
                value: "5432"
              - name: INIT_POSTGRES_DBNAME
                valueFrom:
                  secretKeyRef:
                    name: umami-secret
                    key: UMAMI_DBNAME
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: umami-secret
                    key: UMAMI_DB_USER
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: umami-secret
                    key: UMAMI_DB_PASS
              - name: INIT_POSTGRES_SUPER_USER
                valueFrom:
                  secretKeyRef:
                    name: cluster-secrets
                    key: POSTGRES_SUPER_USER
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: cluster-secrets
                    key: POSTGRES_SUPER_PASS
        containers:
          app:
            image:
              repository: ghcr.io/umami-software/umami
              tag: 3.3.0@sha256:87312d334d009ee67ee0d2fba8fed01435547cc468e452243aef5133a9984d48
            envFrom:
              - secretRef:
                  name: umami-secret
            env:
              - name: DATABASE_URL
                value: postgresql://$(UMAMI_DB_USER):$(UMAMI_DB_PASS)@tolstoy-rw.database.svc.cluster.local:5432/$(UMAMI_DBNAME)
              - name: APP_SECRET
                valueFrom:
                  secretKeyRef:
                    name: umami-secret
                    key: APP_SECRET
              - name: PORT
                value: &port 3000
              - name: DISABLE_TELEMETRY
                value: "true"
              - name: LINKS_URL
                value: "https://umm.popov.wtf/q"
              - name: PIXELS_URL
                value: "https://umm.popov.wtf/p"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.popov.wtf"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
