---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: atlas-nl.rya-tone.ts.net
  name: atlas-nl
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: atlas-ru.rya-tone.ts.net
  name: atlas-ru
spec:
  externalName: placeholder
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: atlas-lv.rya-tone.ts.net
  name: atlas-lv
spec:
  externalName: placeholder
  type: ExternalName
