# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-status-token-secret
stringData:
    token: ENC[AES256_GCM,data:8fUvbT3H69jN6Jtz64jwOInakKPWlhiBIbQ1dV9AWqKUgo9kaxPhCfQb7iOwViCbRizdo94SJjJybpPZ/ymCEQAKJW6DAdSScswv4cIgnD/lqqc7YtB6fFBysEzN,iv:VAYrVRkxbA76woiu0hjTDIGs31x71sve6xLspXBNY8w=,tag:z16rjM4JyBMQULXxFdKdDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRlBFTWhYekl6ZGQxSFAw
            Ynk1NVlQWjllVmJhanBIZGFRRTlGN25Jdm5nCkpXVFM5b3RuWkZVcXVNZXh3d0Q4
            NnF6TDVQdmdLTGp3dERkOWp5V3hJS1kKLS0tIFlDYlp2LzRNQzh2bGRodm42dWxJ
            ODRqa0x5WC9xRGJMbHZ1bFdEZlBjalEKvjLNd/2VZB9tMB9ExeEWEBbQQDUmCLGs
            tbTaz/c+WzvtgSOoeEoHytmemCybA2ELN/TWNH1RsB9TVpzOnJ8XuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T05:02:46Z"
    mac: ENC[AES256_GCM,data:qFk3ZxeOukQN6sLVPLBAbdiP5cztqJZLbA9eDMWGjRPMjBiJKpVfyOPCrH3MgPLRMzxQOS2kiUArIeV/5s5PMrRc9XFjCo+QOc5ba1BIyQIS41qfT7UrlokBeDVg5us+3EjD4uXB/OolKi0WFHa+0k9Ghjwpd2/RGC1BnzwTaSA=,iv:cKDM/NRyBxyFW9Aocswn3UdyVLbKbh1z+VqnQYeaPtM=,tag:CZjqiCfkAp5btYa9NEDvLw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
