apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Y+h26di4IGFoqG8yMF/Z2r31DryxUgVp3FXyq3pP,iv:6BqDnaj8r5VIrqf4mvMR19/0NKVSBxl+ZSbB4czZ/Eg=,tag:/benCuItWW14R+sdh5Y4pg==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:uIQDuqPCyXI=,iv:1pJ092dHg5q3xGTXvjwNjqScf3SwPs/0kURT/wwAupQ=,tag:pqSO84HZVdjzAkIuJZMlVQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3NKoe+d914ejIukZFAz17g==,iv:DQ5X2n3Rou0CVzLP98acW0XDBKGS3ATAqWKlVYh9zlU=,tag:xK9jsWfIWkZn190pFBgUCg==,type:str]
    OPENCLAW_HOOKS_TOKEN: ENC[AES256_GCM,data:v2oKw6iIj+O+vqSKCnS3xqwoCChTQGtWrMZUAEfqeQh/eL7ifXVHc74RP8WO3pHGVXDlseolFyRVnfWaP9hvUg==,iv:MS16YH742uyvpnIWNzyW3PW4LC6K34otW+f/KbM27Nk=,tag:AbfnWymfjK6yLIiS81t5oQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:tDWWMBw5P024lreh066Ze8Wdie5Z7fY+EZzeMYVIf8pYsWGeV8FeyA==,iv:pVUNYp2mMarHywpefngzDf4hsQkYxTPZ0VE1HZqrHtw=,tag:wCMPNh5nBBi5juZF5DpeNg==,type:str]
sops:
    age:
        - recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL2lnK1U0dCticDlSWVZm
            N3NGenBhS3JuLzU5YTJLWnFIY1N4RUthMkhrCit4QmhKSHgvaExnSzZhQUxXQndO
            RU5nLzNNSW9ZMmxyV3BaQ2I1a2IzazgKLS0tIEwwUEI2V3V5ZWlMUG5UdTFkTTlT
            Skp0aUVndEVxekxqV2tDbTI4SU4vWjQKDqSVjGNLLFMOHnbGzCSzAwG3mDPujWTs
            BwbCVMiELQFyedCH93RC0ftjhvmZUL4ce70bUiphAourouuHwUnh3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T07:15:19Z"
    mac: ENC[AES256_GCM,data:Nc0Sgc1kwZDK9sWN6/VwBUTi0rzqSu9vlHld1VSh8mNsmq8BimJvSEdJTaZhQV15BGygBokuUc/EhY416wba9xOgPIzVQccc19fSobe0eZ6w+uU16rZkcBXlS1qtrpxAfAZj5+tXDPYQxh82BG8crxwT1kfFfaBlex4N+r3OB0w=,iv:PkgJ7UFlvmkH7pRfmMCWteihmisLerOGybTYXqvgQXs=,tag:yBH29qIskrM41c+M93vZZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
