apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Y+h26di4IGFoqG8yMF/Z2r31DryxUgVp3FXyq3pP,iv:6BqDnaj8r5VIrqf4mvMR19/0NKVSBxl+ZSbB4czZ/Eg=,tag:/benCuItWW14R+sdh5Y4pg==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:uIQDuqPCyXI=,iv:1pJ092dHg5q3xGTXvjwNjqScf3SwPs/0kURT/wwAupQ=,tag:pqSO84HZVdjzAkIuJZMlVQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3NKoe+d914ejIukZFAz17g==,iv:DQ5X2n3Rou0CVzLP98acW0XDBKGS3ATAqWKlVYh9zlU=,tag:xK9jsWfIWkZn190pFBgUCg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:tDWWMBw5P024lreh066Ze8Wdie5Z7fY+EZzeMYVIf8pYsWGeV8FeyA==,iv:pVUNYp2mMarHywpefngzDf4hsQkYxTPZ0VE1HZqrHtw=,tag:wCMPNh5nBBi5juZF5DpeNg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:/dxLBhRVL47lnt0a7SBorBigzuuAlRbqc/8vQ8mZMaOxPBVkLAZTPAYFDb37xgQKt6LrzxVUb7lLIAWuLATHUqx6lKzNAXeJnK0I8ULvGyaDuswLBl/MY2xsLaNmpU0iSA77oCGvNZfQaSs04n3upaIyvKSjmPvP5FTJIhb1aOELj62bmYmNEzuTQqTFerS4+WxxLmnCGOfOx7xpyxAG9MnpXO8=,iv:4ZxcOXw8t4Bm5NavSZiNroJ+4Db7HKoWG8Jt5+sKFNk=,tag:k/TONJMcAoxNDf+/UWlFgQ==,type:str]
    LLM_ANTHROPIC_API_KEY: ENC[AES256_GCM,data:EIqeYCOJ2NMx0I32fk8/yMi4g47lVukRiLdTjvbxuRaYeh38xWBiYUhE+n5mja+0pPOouV9D/sWngKlSdr5E7a1dJ0yKaAdtmNIUP8iS1s+t6R37IvjIdC/82oDjyo/obCq9gZrMWSQyfyfK,iv:ZEOlSq9lNZmPjT+E87uUQ4+yDOmULZQrlWmn9iY846k=,tag:bMYzUzA5zqKk+G/2veDdhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL2lnK1U0dCticDlSWVZm
            N3NGenBhS3JuLzU5YTJLWnFIY1N4RUthMkhrCit4QmhKSHgvaExnSzZhQUxXQndO
            RU5nLzNNSW9ZMmxyV3BaQ2I1a2IzazgKLS0tIEwwUEI2V3V5ZWlMUG5UdTFkTTlT
            Skp0aUVndEVxekxqV2tDbTI4SU4vWjQKDqSVjGNLLFMOHnbGzCSzAwG3mDPujWTs
            BwbCVMiELQFyedCH93RC0ftjhvmZUL4ce70bUiphAourouuHwUnh3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mjjargxqwmwdgq02az90uqjg626nzy69f0aqtgurhkuj3ya33ffsvwzve0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T06:53:53Z"
    mac: ENC[AES256_GCM,data:Qxz3mo540ZP14Gy/RmQIvUsQCZl/wGSJ57YT62bCynO73/DhbLxWUUVdBgaPwsTqJwCIm7WA4WvY0frWZ0jm+4ykKez3Q0rDmMdWwQO9nwS7NoIpppQnYEtKKtFg/H59dyzAjw5W3bQtMARp/kdUns79+FkDKgHF9ZLuatDaN7M=,iv:qA+GfmvAYFH7G9TxModdgD/KEnVUFsdX/PZeoz8Y0D8=,tag:/40AZ8X2x+xQbDU/mttNAg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
