---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.5.0
    digest: sha256:b682e4262317a29dd15b6210ac3944110447f0d7c3b121ec04a65dda679c46f4
  url: oci://ghcr.io/openebs/charts/openebs
