---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Tests"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: devenv
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Pre-initialize
        shell: devenv shell bash -- -e {0}
        run: |
          task ansible:bootstrap

      - name: Run devenv test
        run: devenv test
