---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Tests"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: tolkonepiu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community,devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Pre-initialize
        shell: devenv shell bash -- -e {0}
        run: |
          task ansible:bootstrap

      - name: Run devenv test
        run: devenv test
