---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Tests"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Preinstall roles for ansible-lint
        run: devenv shell task ansible:bootstrap

      - name: Run devenv test
        run: devenv test
