---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.36.0+k3s1
  serviceAccountName: system-upgrade-controller
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: DoesNotExist }
  prepare:
    image: rancher/k3s-upgrade:v1.32.13-k3s1@sha256:a51530d62449b469b7c76ec191117ad1cc3325cab8f0bbcc0991aa6f9a631962
    args: ["prepare", "server"]
  upgrade:
    image: rancher/k3s-upgrade:v1.32.13-k3s1@sha256:a51530d62449b469b7c76ec191117ad1cc3325cab8f0bbcc0991aa6f9a631962
