---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: v1.37.0+k3s1
  serviceAccountName: system-upgrade-controller
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: DoesNotExist }
  prepare:
    image: rancher/k3s-upgrade:v1.37.0-k3s1@sha256:7a83f0637c81168a7560000f2bdc972c88f621d7a9872e6afe3bba2d40964d74
    args: ["prepare", "server"]
  upgrade:
    image: rancher/k3s-upgrade:v1.37.0-k3s1@sha256:7a83f0637c81168a7560000f2bdc972c88f621d7a9872e6afe3bba2d40964d74
